project_id = "nqdausnuvczxvocslzrj"

[functions.store-oauth-tokens]
verify_jwt = false

[functions.index-documents]
verify_jwt = false

[functions.search-documents]
verify_jwt = false

[functions.sync-calendar]
verify_jwt = false

[functions.prepare-meeting]
verify_jwt = false